### ISSUE TITLE
This repo lacks a license? GPL?

### ISSUE THREAD

**Issue by davidkrauser** [chrisglass/ubuntu-old-fashioned#26]

**Comment by chrisglass** [comment]
That is a great point.

I suspect all previous contributors would be fine with GPL v.3. 
Let's ping and ask :)

@OddBloke @philroche @rcj4747 @codyshepherd  @sparkiegeek ?

**Comment by sparkiegeek** [comment]
+1

**Comment by philroche** [comment]
+1

**Comment by codyshepherd** [comment]
+1

**Comment by rcj4747** [comment]
+1

**Comment by chrisglass** [comment]
The code now has a shiny new GPL v.3 LICENSE file. I'll close this now.

Thanks!
