### ISSUE TITLE
Adding new collaborators - j5awry

### ISSUE THREAD

**Issue by philroche** [chrisglass/ubuntu-old-fashioned#63]
@chrisglass Can you add j5awry as a collaborator? He is a member of our Canonical CPC and has made great contributions to ubuntu-old-fashioned. Recently adding support for building arm64 images

**Comment by chrisglass** [comment]
Heya! Sure thing - I'll add him in right now.

Welcome @j5awry !

**Comment by philroche** [comment]
Thank you \o
